#!/bin/python3

import traceback

from nrsuite_lib.cli import main
from nrsuite_lib.config import LOG_FILE, init_storage

init_storage()

if __name__ == "__main__":
    try:
        main()
    except Exception:
        with open(LOG_FILE, "a") as f:
            f.write(traceback.format_exc())
